import { Component, OnInit } from '@angular/core';
import { Property } from '../property';

@Component({
  selector: 'app-related-list',
  templateUrl: './related-list.component.html',
  styleUrls: ['./related-list.component.css']
})
export class RelatedListComponent implements OnInit {
  relatedProperties: Property[] = [
    {
      id: 11,
      propertyTitle: '',
      bedrooms: 3,
      address: {city: 'Addis Ababa', subCity: 'Bole', area: 'Bole'},
      price: {amount: 2000, type: 'Negotiable'},
      postCreator: 'edelala',
      propertyImages: ['assets/1.jpg', 'assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg'],
      amenities: ['Fixed Kitchen Cabinet', 'Balcony'],
      bathrooms: 2,
      levels: 1,
      areaInM2: 400,
    },
    {
      id: 12,
      propertyTitle: '',
      bedrooms: 8,
      address: {city: 'Addis Ababa', subCity: 'Bole', area: 'Hayahulet'},
      price: {amount: 10000, type: 'Negotiable'},
      postCreator: 'mahletg',
      propertyImages: ['assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg'],
      amenities: [],
    },
    {
      id: 13,
      propertyTitle: 'Quick Rental Needed Great Price',
      bedrooms: 3,
      address: {city: 'Addis Ababa', area: 'Yerer'},
      price: {amount: 19000, type: 'Negotiable'},
      postCreator: 'mesimesi',
      propertyImages: ['assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg', 'assets/2.jpg'],
      amenities: ['Backyard', 'Nice View'],
    },
    {
      id: 11,
      propertyTitle: '',
      bedrooms: 3,
      address: {city: 'Addis Ababa', subCity: 'Bole', area: 'Bole'},
      price: {amount: 2000, type: 'Negotiable'},
      postCreator: 'edelala',
      propertyImages: ['assets/1.jpg', 'assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg'],
      amenities: ['Fixed Kitchen Cabinet', 'Balcony'],
      bathrooms: 2,
      levels: 1,
      areaInM2: 400,
    },
    {
      id: 12,
      propertyTitle: '',
      bedrooms: 8,
      address: {city: 'Addis Ababa', subCity: 'Bole', area: 'Hayahulet'},
      price: {amount: 10000, type: 'Negotiable'},
      postCreator: 'mahletg',
      propertyImages: ['assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg'],
      amenities: [],
    },
    {
      id: 13,
      propertyTitle: 'Quick Rental Needed Great Price',
      bedrooms: 3,
      address: {city: 'Addis Ababa', area: 'Yerer'},
      price: {amount: 19000, type: 'Negotiable'},
      postCreator: 'mesimesi',
      propertyImages: ['assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg', 'assets/2.jpg'],
      amenities: ['Backyard', 'Nice View'],
    },
    {
      id: 11,
      propertyTitle: '',
      bedrooms: 3,
      address: {city: 'Addis Ababa', subCity: 'Bole', area: 'Bole'},
      price: {amount: 2000, type: 'Negotiable'},
      postCreator: 'edelala',
      propertyImages: ['assets/1.jpg', 'assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg'],
      amenities: ['Fixed Kitchen Cabinet', 'Balcony'],
      bathrooms: 2,
      levels: 1,
      areaInM2: 400,
    },
    {
      id: 12,
      propertyTitle: '',
      bedrooms: 8,
      address: {city: 'Addis Ababa', subCity: 'Bole', area: 'Hayahulet'},
      price: {amount: 10000, type: 'Negotiable'},
      postCreator: 'mahletg',
      propertyImages: ['assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg'],
      amenities: [],
    },
    {
      id: 13,
      propertyTitle: 'Quick Rental Needed Great Price',
      bedrooms: 3,
      address: {city: 'Addis Ababa', area: 'Yerer'},
      price: {amount: 19000, type: 'Negotiable'},
      postCreator: 'mesimesi',
      propertyImages: ['assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg', 'assets/2.jpg'],
      amenities: ['Backyard', 'Nice View'],
    },
    {
      id: 11,
      propertyTitle: '',
      bedrooms: 3,
      address: {city: 'Addis Ababa', subCity: 'Bole', area: 'Bole'},
      price: {amount: 2000, type: 'Negotiable'},
      postCreator: 'edelala',
      propertyImages: ['assets/1.jpg', 'assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg'],
      amenities: ['Fixed Kitchen Cabinet', 'Balcony'],
      bathrooms: 2,
      levels: 1,
      areaInM2: 400,
    },
    {
      id: 12,
      propertyTitle: '',
      bedrooms: 8,
      address: {city: 'Addis Ababa', subCity: 'Bole', area: 'Hayahulet'},
      price: {amount: 10000, type: 'Negotiable'},
      postCreator: 'mahletg',
      propertyImages: ['assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg'],
      amenities: [],
    },
    {
      id: 13,
      propertyTitle: 'Quick Rental Needed Great Price',
      bedrooms: 3,
      address: {city: 'Addis Ababa', area: 'Yerer'},
      price: {amount: 19000, type: 'Negotiable'},
      postCreator: 'mesimesi',
      propertyImages: ['assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg', 'assets/2.jpg'],
      amenities: ['Backyard', 'Nice View'],
    },
    {
      id: 11,
      propertyTitle: '',
      bedrooms: 3,
      address: {city: 'Addis Ababa', subCity: 'Bole', area: 'Bole'},
      price: {amount: 2000, type: 'Negotiable'},
      postCreator: 'edelala',
      propertyImages: ['assets/1.jpg', 'assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg'],
      amenities: ['Fixed Kitchen Cabinet', 'Balcony'],
      bathrooms: 2,
      levels: 1,
      areaInM2: 400,
    },
    {
      id: 12,
      propertyTitle: '',
      bedrooms: 8,
      address: {city: 'Addis Ababa', subCity: 'Bole', area: 'Hayahulet'},
      price: {amount: 10000, type: 'Negotiable'},
      postCreator: 'mahletg',
      propertyImages: ['assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg'],
      amenities: [],
    },
    {
      id: 13,
      propertyTitle: 'Quick Rental Needed Great Price',
      bedrooms: 3,
      address: {city: 'Addis Ababa', area: 'Yerer'},
      price: {amount: 19000, type: 'Negotiable'},
      postCreator: 'mesimesi',
      propertyImages: ['assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg', 'assets/2.jpg'],
      amenities: ['Backyard', 'Nice View'],
    },
  ].splice(0, 6) as Property[];

  constructor() { }

  ngOnInit(): void {
  }

}
