import { Property } from './property';

export const MOCKPROPERTIES: Property[] = [
  {
    id: 11,
    propertyTitle: '',
    bedrooms: 3,
    location: 'Bole, Addis Ababa',
    listPrice: 2000,
    priceType: 'Fixed',
    postCreator: 'edelala',
    propertyImages: ['assets/1.jpg', 'assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg'],
    amenities: ['Fixed Kitchen Cabinet', 'Balcony'],
    bathrooms: 2,
    levels: 'Ground',
    areaInM2: 400,
  },
  {
    id: 12,
    propertyTitle: '',
    bedrooms: 8,
    location: 'Hayahulet, Addis Ababa',
    listPrice: 10000,
    priceType: 'Negotiable',
    postCreator: 'mahletg',
    propertyImages: ['assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg'],
    amenities: [],
  },
  {
    id: 13,
    propertyTitle: 'Quick Rental Needed Great Price',
    bedrooms: 3,
    location: 'Yerer, Addis Ababa',
    listPrice: 19000,
    priceType: 'Negotiable',
    postCreator: 'mesimesi',
    propertyImages: ['assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg', 'assets/2.jpg'],
    amenities: ['Backyard', 'Nice View'],
  },
  {
    id: 14,
    propertyTitle: '',
    bedrooms: 3,
    location: 'Addis Ketema, Addis Ababa',
    listPrice: 49000,
    priceType: 'Negotiable',
    postCreator: 'edelala',
    propertyImages: ['assets/4.jpg', 'assets/1.jpg', 'assets/2.jpg', 'assets/3.jpg'],
    amenities: ['Backyard', 'Nice View'],
  },
  {
    id: 15,
    propertyTitle: '',
    bedrooms: 3,
    location: 'Merkato, Addis Ababa',
    listPrice: 12000,
    priceType: 'Fixed',
    postCreator: 'edelala',
    propertyImages: ['assets/1.jpg', 'assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg'],
    amenities: ['Backyard', 'Nice View'],
  },
  {
    id: 16,
    propertyTitle: '',
    bedrooms: 3,
    location: 'Meskel Flower, Addis Ababa',
    listPrice: 25000,
    priceType: 'Negotiable',
    postCreator: 'edelala',
    propertyImages: ['assets/2.jpg', 'assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg'],
    amenities: ['Backyard', 'Nice View'],
  },
  {
    id: 17,
    propertyTitle: '',
    bedrooms: 3,
    location: 'Gotera, Addis Ababa',
    listPrice: 29000,
    priceType: 'Fixed',
    postCreator: 'allhouseset',
    propertyImages: ['assets/3.jpg', 'assets/4.jpg', 'assets/1.jpg', 'assets/2.jpg'],
    amenities: ['Backyard', 'Nice View'],
  },
];